### ISSUE TITLE
Add shared search params to hyperopt docs

### ISSUE THREAD

**Issue by arnavgarg1** [ludwig-ai/ludwig-docs#171]
In conjunction with [this](https://github.com/ludwig-ai/ludwig/pull/2133) PR, Ludwig hyperopt documentation should be updated to indicate that users can now specify default search space parameters within hyperopt so that they just define the search space once. 

For e.g., 

```yaml
hyperopt:
    goal: minimize
    parameters:
        trainer.learning_rate:
            lower: 0.0001
            upper: 0.01
            space: loguniform
        defaults.text.cell_type:
            space: choice
            categories: ["lstm", "rnn", "gru"]
        defaults.category.vocab_size:
            space: randint
            lower: 4
            upper: 8
        ....
    ....
```
